name: Build do Projeto projeto-reactjs-portifolio-app

on: [push]  # Disparar o fluxo de trabalho quando houver push para o repositório

jobs:
  build:
    runs-on: ubuntu-latest  # O ambiente em que o fluxo de trabalho será executado

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Construir a imagem Docker e implantar no NGINX
      run: |
        docker build -t projeto-reactjs-portifolio-app .
        docker run -d -p 80:80 projeto-reactjs-portifolio-app
