name: CI/CD Pipeline Portifolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and push Docker image
        run: |
          docker build -t adrianovolter/portifolio-2023-app .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push adrianovolter/portifolio-2023-app:latest

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b update-branch
          git commit --allow-empty -m "Automated commit for pull request"
          git push origin update-branch
          hub pull-request -b main -h update-branch -m "Update Docker image"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}